# Generated by Django 4.1.4 on 2022-12-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='discription',
            new_name='description',
        ),
    ]
